version: '3.8'

services:
  nod-detector:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount the local input directory to the container's /data/input
      - ./data/input:/data/input
      # Mount the local output directory to the container's /data/output
      - ./data/output:/data/output
    # Example command (uncomment and modify as needed):
    # command: python -m nod_detector /data/input/input_video.mp4 -o /data/output/output_video.mp4 -v
    # To run with GPU support (uncomment if you have NVIDIA GPU and nvidia-docker installed):
    # runtime: nvidia
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    #   - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    #   - NVIDIA_REQUIRE_CUDA=cuda>=11.7
    tty: true  # Keeps the container running for interactive use
