"""Sphinx configuration for Nod Detector documentation."""

import os
import sys
from datetime import datetime

# Add the project root to the Python path
sys.path.insert(0, os.path.abspath(".."))

# -- Project information -----------------------------------------------------
project = "Nod Detector"
copyright = f"{datetime.now().year}, Kagan Kucukaytekin"
author = "Kagan Kucukaytekin"
release = "0.1.0"
version = "0.1"

# -- General configuration ---------------------------------------------------
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",
    "sphinx.ext.githubpages",
    "sphinx_rtd_theme",
]

# Paths that contain templates
templates_path = ["_templates"]

# File patterns to exclude
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store", "**.ipynb_checkpoints"]

# The suffix of source filenames
source_suffix = ".rst"

# The master toctree document
master_doc = "index"

# The language for content autogenerated by Sphinx
language = "en"

# -- Options for HTML output -------------------------------------------------
html_theme = "sphinx_rtd_theme"

# Theme options
html_theme_options = {
    "collapse_navigation": False,
    "titles_only": True
}

# Paths that contain custom static files
html_static_path = ["_static"]

# -- Extension configuration -------------------------------------------------
# Autodoc settings
autodoc_default_options = {
    'members': True,
    'member-order': 'bysource',
    'show-inheritance': True,
}

# Napoleon settings
napoleon_google_docstring = True
napoleon_include_init_with_doc = True
