name: CI

on:
  push:
    branches: [ '**' ]  # Run on all branches
  pull_request:
    branches: [ '**' ]  # Run on PRs from any branch

jobs:
  test:
    name: Python ${{ matrix.python-version }} (${{ github.ref_name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]  # Test against these Python versions

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Python environment
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --upgrade pip setuptools wheel
        pip list

    - name: Install package in development mode
      run: |
        pip install -e ".[dev]"

    - name: Install development dependencies
      run: |
        pip install -r requirements-dev.txt || pip install -e '.[dev]'

    - name: Lint with flake8
      run: flake8 src

    - name: Check types with mypy
      run: mypy -p nod_detector

    - name: Run tests
      run: |
        pip list
        python -c "import sys; print('Python version:', sys.version)"
        pytest tests/ -v
